'use strict';

import addPhoneProlapse from './modules/telephoneList';
import openBurgerMenu from './modules/openBurgerMenu';
import footerScroll from './modules/footerScroll';
import addFullPriceList from './modules/fullPriceList';
import phoneMask from './modules/phoneMask';
import togglePrivacy from './modules/togglePrivacy';
import formulaItemDescribe from './modules/formulaItemDescribe';
import sendForms from './modules/sendForm';
import renderPopup from './modules/renderPopup';
import toggleConsult from './modules/toggleConsult';
import accord from './modules/accord';
import tabsWork from './modules/tabsWork';
import sliderRepair from './modules/sliderRepair';
//import sliderFormula from './modules/formulaSlider';
import docTabs from './modules/docTabs';
import sliderPortfolio from './modules/sliderPortfolio';
import sliderRewievs from './modules/sliderRewiews';
import togglePopupPortfolio from './modules/togglePortfolio';
import partnersCarousel from './modules/partnersCarousel';

addPhoneProlapse();
openBurgerMenu();
footerScroll();
addFullPriceList();
phoneMask();
togglePrivacy();
formulaItemDescribe();
sendForms();
renderPopup();
toggleConsult();
accord();
tabsWork();
sliderRepair();
docTabs();
//sliderFormula();
sliderPortfolio();
sliderRewievs();
togglePopupPortfolio();
partnersCarousel()