'use strict';

import 'nodelist-foreach-polyfill';
import elementClosest from 'element-closest';
import "@babel/polyfill";
import 'fetch-polyfill';
import 'ie11-scroll-into-view';
import 'cross-browser-polyfill';
elementClosest(window);

import addPhoneProlapse from './modules/telephoneList';
import openBurgerMenu from './modules/openBurgerMenu';
import footerScroll from './modules/footerScroll';
import addFullPriceList from './modules/fullPriceList';
import phoneMask from './modules/phoneMask';
import togglePrivacy from './modules/togglePrivacy';
import formulaItemDescribe from './modules/formulaItemDescribe';
import sendForms from './modules/sendForm';
import renderPopup from './modules/renderPopup';
import toggleConsult from './modules/toggleConsult';
import accord from './modules/accord';
import tabsWork from './modules/tabsWork';
import sliderRepair from './modules/sliderRepair';
import mobileFormulaSlider from './modules/formulaSlider';
import docTabs from './modules/docTabs';
import sliderPortfolio from './modules/sliderPortfolio';
import sliderRewievs from './modules/sliderRewiews';
import togglePopupPortfolio from './modules/togglePortfolio';
import partnersCarousel from './modules/partnersCarousel';
import sliderProblems from './modules/sliderProblems';
import sliderWorks from './modules/sliderWorks';
import problemDescribe from './modules/problemItemDescribe';

addPhoneProlapse();
openBurgerMenu();
footerScroll();
addFullPriceList();
phoneMask();
togglePrivacy();
formulaItemDescribe();
sendForms();
renderPopup();
toggleConsult();
accord();
tabsWork();
sliderRepair();
docTabs();
mobileFormulaSlider();
sliderPortfolio();
sliderRewievs();
togglePopupPortfolio();
partnersCarousel();
sliderProblems();
sliderWorks();
problemDescribe();
window.addEventListener('resize', () => {
    formulaItemDescribe();
    docTabs();
    mobileFormulaSlider();
    sliderPortfolio();
    partnersCarousel();
    sliderProblems();
    sliderWorks();
});